import {
  SiPython,
  SiPandas,
  SiScikitlearn,
  SiDocker,
  SiReact,
  SiJavascript,
  SiTypescript,
  SiNodedotjs,
  SiHtml5,
  SiCss,
  SiApachespark,
  SiApacheairflow,
  SiGooglecloud,
  SiFastapi,
  SiGooglebigquery,
  SiGithubactions,
  SiRedis,
  SiPostgresql,
  SiSnowflake,
  SiApachekafka,
  SiGo,
  SiTerraform,
  SiGnubash,
  SiOpenjdk,
  SiCplusplus,
  SiYaml,
  SiNextdotjs,
  SiGithub,
  SiPlotly,
} from "react-icons/si";
import { Cpu, Boxes, Workflow, Cloud, Database, GitBranch, Container, Sigma, Code2, Network, Brain, Bot, Server } from "lucide-react";
import type { ReactNode } from "react";

const map: Record<string, { icon: ReactNode; color: string }> = {
  python: { icon: <SiPython />, color: "#3776AB" },
  pandas: { icon: <SiPandas />, color: "#150458" },
  "scikit-learn": { icon: <SiScikitlearn />, color: "#F7931E" },
  docker: { icon: <SiDocker />, color: "#2496ED" },
  react: { icon: <SiReact />, color: "#61DAFB" },
  javascript: { icon: <SiJavascript />, color: "#F7DF1E" },
  typescript: { icon: <SiTypescript />, color: "#3178C6" },
  "node.js": { icon: <SiNodedotjs />, color: "#5FA04E" },
  nodejs: { icon: <SiNodedotjs />, color: "#5FA04E" },
  html: { icon: <SiHtml5 />, color: "#E34F26" },
  css: { icon: <SiCss />, color: "#1572B6" },
  "apache spark": { icon: <SiApachespark />, color: "#E25A1C" },
  spark: { icon: <SiApachespark />, color: "#E25A1C" },
  "apache airflow": { icon: <SiApacheairflow />, color: "#017CEE" },
  airflow: { icon: <SiApacheairflow />, color: "#017CEE" },
  gcs: { icon: <SiGooglecloud />, color: "#4285F4" },
  gce: { icon: <SiGooglecloud />, color: "#4285F4" },
  "google cloud": { icon: <SiGooglecloud />, color: "#4285F4" },
  gcp: { icon: <SiGooglecloud />, color: "#4285F4" },
  fastapi: { icon: <SiFastapi />, color: "#009688" },
  bigquery: { icon: <SiGooglebigquery />, color: "#669DF6" },
  aws: { icon: <Cloud className="h-3 w-3" />, color: "#FF9900" },
  "aws ecs": { icon: <Cloud className="h-3 w-3" />, color: "#FF9900" },
  "aws ecr": { icon: <Cloud className="h-3 w-3" />, color: "#FF9900" },
  "aws s3": { icon: <Cloud className="h-3 w-3" />, color: "#FF9900" },
  ecs: { icon: <Cloud className="h-3 w-3" />, color: "#FF9900" },
  ecr: { icon: <Cloud className="h-3 w-3" />, color: "#FF9900" },
  ec2: { icon: <Cloud className="h-3 w-3" />, color: "#FF9900" },
  s3: { icon: <Cloud className="h-3 w-3" />, color: "#FF9900" },
  "ci/cd": { icon: <SiGithubactions />, color: "#2088FF" },
  "gitlab ci/cd": { icon: <GitBranch className="h-3 w-3" />, color: "#FC6D26" },
  github: { icon: <SiGithub />, color: "#181717" },
  redis: { icon: <SiRedis />, color: "#DC382D" },
  postgres: { icon: <SiPostgresql />, color: "#4169E1" },
  postgresql: { icon: <SiPostgresql />, color: "#4169E1" },
  snowflake: { icon: <SiSnowflake />, color: "#29B5E8" },
  kafka: { icon: <SiApachekafka />, color: "#231F20" },
  go: { icon: <SiGo />, color: "#00ADD8" },
  golang: { icon: <SiGo />, color: "#00ADD8" },
  terraform: { icon: <SiTerraform />, color: "#7B42BC" },
  bash: { icon: <SiGnubash />, color: "#4EAA25" },
  java: { icon: <SiOpenjdk />, color: "#ED8B00" },
  "c/c++": { icon: <SiCplusplus />, color: "#00599C" },
  "c++": { icon: <SiCplusplus />, color: "#00599C" },
  yaml: { icon: <SiYaml />, color: "#CB171E" },
  next: { icon: <SiNextdotjs />, color: "#000000" },
  "next.js": { icon: <SiNextdotjs />, color: "#000000" },
  matplotlib: { icon: <SiPlotly />, color: "#11557C" },
  seaborn: { icon: <SiPlotly />, color: "#3F4F75" },
  "agentic ai": { icon: <Bot className="h-3 w-3" />, color: "#8B5CF6" },
  "mcp server": { icon: <Workflow className="h-3 w-3" />, color: "#10B981" },
  mcp: { icon: <Workflow className="h-3 w-3" />, color: "#10B981" },
  llm: { icon: <Brain className="h-3 w-3" />, color: "#A855F7" },
  "etl pipelines": { icon: <Workflow className="h-3 w-3" />, color: "#0EA5E9" },
  "distributed systems": { icon: <Network className="h-3 w-3" />, color: "#64748B" },
  sql: { icon: <Database className="h-3 w-3" />, color: "#0EA5E9" },
  r: { icon: <Code2 className="h-3 w-3" />, color: "#276DC3" },
  statistics: { icon: <Sigma className="h-3 w-3" />, color: "#64748B" },
  algorithms: { icon: <Cpu className="h-3 w-3" />, color: "#64748B" },
  kubernetes: { icon: <Container className="h-3 w-3" />, color: "#326CE5" },
  k8s: { icon: <Container className="h-3 w-3" />, color: "#326CE5" },
  server: { icon: <Server className="h-3 w-3" />, color: "#64748B" },
};

export function TechIcon({ name }: { name: string }) {
  const entry = map[name.toLowerCase()];
  if (!entry) return <Boxes className="h-3 w-3 opacity-70" />;
  return (
    <span style={{ color: entry.color }} className="inline-flex text-[13px]">
      {entry.icon}
    </span>
  );
}
